//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuzRus.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CATEGORY_DESCRIPTION {
            get {
                return ResourceManager.GetString("CATEGORY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CATEGORY_NAME {
            get {
                return ResourceManager.GetString("CATEGORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CATEGORY_STATUS {
            get {
                return ResourceManager.GetString("CATEGORY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string CATEGORY_TITLE {
            get {
                return ResourceManager.GetString("CATEGORY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CATEGORY_TYPE {
            get {
                return ResourceManager.GetString("CATEGORY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string COMMENTS_ADD_NEW {
            get {
                return ResourceManager.GetString("COMMENTS_ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comment.
        /// </summary>
        public static string COMMENTS_ENTER_COMMENT {
            get {
                return ResourceManager.GetString("COMMENTS_ENTER_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string COMMENTS_TITLE {
            get {
                return ResourceManager.GetString("COMMENTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string COMMON_ALL {
            get {
                return ResourceManager.GetString("COMMON_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string COMMON_CANCEL {
            get {
                return ResourceManager.GetString("COMMON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string COMMON_CLOSE {
            get {
                return ResourceManager.GetString("COMMON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image.
        /// </summary>
        public static string COMMON_DELETE_IMAGE {
            get {
                return ResourceManager.GetString("COMMON_DELETE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string COMMON_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("COMMON_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string COMMON_TABLES {
            get {
                return ResourceManager.GetString("COMMON_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CUSTOMER_ADDRESS {
            get {
                return ResourceManager.GetString("CUSTOMER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your business address.
        /// </summary>
        public static string CUSTOMER_ADDRESS_PLACEHOLDER {
            get {
                return ResourceManager.GetString("CUSTOMER_ADDRESS_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CUSTOMER_CITY {
            get {
                return ResourceManager.GetString("CUSTOMER_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your business city.
        /// </summary>
        public static string CUSTOMER_CITY_PLACEHOLDER {
            get {
                return ResourceManager.GetString("CUSTOMER_CITY_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string CUSTOMER_COMPANY {
            get {
                return ResourceManager.GetString("CUSTOMER_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your business company name.
        /// </summary>
        public static string CUSTOMER_COMPANY_PLACEHOLDER {
            get {
                return ResourceManager.GetString("CUSTOMER_COMPANY_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen Printer.
        /// </summary>
        public static string CUSTOMER_KITCHEN_PRINTER {
            get {
                return ResourceManager.GetString("CUSTOMER_KITCHEN_PRINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string CUSTOMER_LANGUAGE {
            get {
                return ResourceManager.GetString("CUSTOMER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string CUSTOMER_MODULES {
            get {
                return ResourceManager.GetString("CUSTOMER_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string CUSTOMER_PHONE {
            get {
                return ResourceManager.GetString("CUSTOMER_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your business phone number.
        /// </summary>
        public static string CUSTOMER_PHONE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("CUSTOMER_PHONE_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Printer.
        /// </summary>
        public static string CUSTOMER_POS_PRINTER {
            get {
                return ResourceManager.GetString("CUSTOMER_POS_PRINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string CUSTOMER_STATE {
            get {
                return ResourceManager.GetString("CUSTOMER_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string CUSTOMER_TAB_INFORMATION {
            get {
                return ResourceManager.GetString("CUSTOMER_TAB_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string CUSTOMER_TAB_MODULES {
            get {
                return ResourceManager.GetString("CUSTOMER_TAB_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string CUSTOMER_TAB_SETTINGS {
            get {
                return ResourceManager.GetString("CUSTOMER_TAB_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string CUSTOMER_TAX {
            get {
                return ResourceManager.GetString("CUSTOMER_TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company form.
        /// </summary>
        public static string CUSTOMER_TITLE {
            get {
                return ResourceManager.GetString("CUSTOMER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string CUSTOMER_ZIP {
            get {
                return ResourceManager.GetString("CUSTOMER_ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your business zip.
        /// </summary>
        public static string CUSTOMER_ZIP_PLACEHOLDER {
            get {
                return ResourceManager.GetString("CUSTOMER_ZIP_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        public static string FLOOR_CHANGE_NAME {
            get {
                return ResourceManager.GetString("FLOOR_CHANGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change shape.
        /// </summary>
        public static string FLOOR_CHANGE_SHAPE {
            get {
                return ResourceManager.GetString("FLOOR_CHANGE_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete floor.
        /// </summary>
        public static string FLOOR_DELETE {
            get {
                return ResourceManager.GetString("FLOOR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit floor.
        /// </summary>
        public static string FLOOR_EDIT {
            get {
                return ResourceManager.GetString("FLOOR_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter table dsescription.
        /// </summary>
        public static string FLOOR_ENTER_TABLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("FLOOR_ENTER_TABLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter table name.
        /// </summary>
        public static string FLOOR_ENTER_TABLE_NAME {
            get {
                return ResourceManager.GetString("FLOOR_ENTER_TABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors:.
        /// </summary>
        public static string FLOOR_FLOORS {
            get {
                return ResourceManager.GetString("FLOOR_FLOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New floor.
        /// </summary>
        public static string FLOOR_NEW {
            get {
                return ResourceManager.GetString("FLOOR_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string FLOOR_TABLE_CIRCLE {
            get {
                return ResourceManager.GetString("FLOOR_TABLE_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit table.
        /// </summary>
        public static string FLOOR_TABLE_EDIT {
            get {
                return ResourceManager.GetString("FLOOR_TABLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filler.
        /// </summary>
        public static string FLOOR_TABLE_FILLER {
            get {
                return ResourceManager.GetString("FLOOR_TABLE_FILLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string FLOOR_TABLE_ROUND {
            get {
                return ResourceManager.GetString("FLOOR_TABLE_ROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table shape:.
        /// </summary>
        public static string FLOOR_TABLE_SHAPE {
            get {
                return ResourceManager.GetString("FLOOR_TABLE_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string FLOOR_TABLE_SQUARE {
            get {
                return ResourceManager.GetString("FLOOR_TABLE_SQUARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor setup.
        /// </summary>
        public static string FLOOR_TITLE {
            get {
                return ResourceManager.GetString("FLOOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LOGIN_BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string LOGIN_BUTTON_SIGN_IN {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string LOGIN_BUTTON_TRY_AGAIN {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in failed.
        /// </summary>
        public static string LOGIN_MESSAGE_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_MESSAGE_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check you credentials and try again. Close this window to continue..
        /// </summary>
        public static string LOGIN_TEXT_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_TEXT_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LOGIN_TEXTBOX_EMAIL_PLACEHOLDER {
            get {
                return ResourceManager.GetString("LOGIN_TEXTBOX_EMAIL_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LOGIN_TEXTBOX_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("LOGIN_TEXTBOX_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in.
        /// </summary>
        public static string LOGIN_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string MENU_COMPANY {
            get {
                return ResourceManager.GetString("MENU_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string MENU_LOG_OUT {
            get {
                return ResourceManager.GetString("MENU_LOG_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to.
        /// </summary>
        public static string MENU_NAVIGATE_TO {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string MENU_NAVIGATE_TO_FLOOR {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        public static string MENU_NAVIGATE_TO_FLOORS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_FLOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string MENU_NAVIGATE_TO_ITEMS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        public static string MENU_NAVIGATE_TO_KITCHEN {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_KITCHEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string MENU_NAVIGATE_TO_MENUS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_MENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        public static string MENU_NAVIGATE_TO_MONITORS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_MONITORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string MENU_NAVIGATE_TO_ORDER {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string MENU_NAVIGATE_TO_ORDERS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string MENU_NAVIGATE_TO_SERVICES {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MENU_PROFILE {
            get {
                return ResourceManager.GetString("MENU_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string MENU_REPORTS {
            get {
                return ResourceManager.GetString("MENU_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string MENU_REPORTS_INVENTORY {
            get {
                return ResourceManager.GetString("MENU_REPORTS_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string MENU_REPORTS_SALES {
            get {
                return ResourceManager.GetString("MENU_REPORTS_SALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MENU_USERS {
            get {
                return ResourceManager.GetString("MENU_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string MONITOR_TITLE {
            get {
                return ResourceManager.GetString("MONITOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add application modules.
        /// </summary>
        public static string REGISTRATION_APPLICATION_MODULES {
            get {
                return ResourceManager.GetString("REGISTRATION_APPLICATION_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your business address.
        /// </summary>
        public static string REGISTRATION_BUSINESS_ADDRESS1 {
            get {
                return ResourceManager.GetString("REGISTRATION_BUSINESS_ADDRESS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address if needed.
        /// </summary>
        public static string REGISTRATION_BUSINESS_ADDRESS2 {
            get {
                return ResourceManager.GetString("REGISTRATION_BUSINESS_ADDRESS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter city.
        /// </summary>
        public static string REGISTRATION_BUSINESS_CITY {
            get {
                return ResourceManager.GetString("REGISTRATION_BUSINESS_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your business information.
        /// </summary>
        public static string REGISTRATION_BUSINESS_INFORMATION {
            get {
                return ResourceManager.GetString("REGISTRATION_BUSINESS_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your business name.
        /// </summary>
        public static string REGISTRATION_BUSINESS_NAME {
            get {
                return ResourceManager.GetString("REGISTRATION_BUSINESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        public static string REGISTRATION_BUSINESS_PHONE {
            get {
                return ResourceManager.GetString("REGISTRATION_BUSINESS_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string REGISTRATION_BUSINESS_STATE {
            get {
                return ResourceManager.GetString("REGISTRATION_BUSINESS_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter zip.
        /// </summary>
        public static string REGISTRATION_BUSINESS_ZIP {
            get {
                return ResourceManager.GetString("REGISTRATION_BUSINESS_ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password one more time.
        /// </summary>
        public static string REGISTRATION_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("REGISTRATION_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter  your email address.
        /// </summary>
        public static string REGISTRATION_EMAIL {
            get {
                return ResourceManager.GetString("REGISTRATION_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        public static string REGISTRATION_FIRST_NAME {
            get {
                return ResourceManager.GetString("REGISTRATION_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        public static string REGISTRATION_LAST_NAME {
            get {
                return ResourceManager.GetString("REGISTRATION_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your mobile phone.
        /// </summary>
        public static string REGISTRATION_MOBILE_PHONE {
            get {
                return ResourceManager.GetString("REGISTRATION_MOBILE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password one more time.
        /// </summary>
        public static string REGISTRATION_PASSWORD {
            get {
                return ResourceManager.GetString("REGISTRATION_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match confirmation password. Please revise..
        /// </summary>
        public static string REGISTRATION_PASSWORD_FAILED {
            get {
                return ResourceManager.GetString("REGISTRATION_PASSWORD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your personal information.
        /// </summary>
        public static string REGISTRATION_PERSONAL_INFORMATION {
            get {
                return ResourceManager.GetString("REGISTRATION_PERSONAL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string REGISTRATION_TAX {
            get {
                return ResourceManager.GetString("REGISTRATION_TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your work phone.
        /// </summary>
        public static string REGISTRATION_WORK_PHONE {
            get {
                return ResourceManager.GetString("REGISTRATION_WORK_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Form.
        /// </summary>
        public static string USER_FORM_TITLE {
            get {
                return ResourceManager.GetString("USER_FORM_TITLE", resourceCulture);
            }
        }
    }
}
