//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuzRus.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LOGIN_BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LOGIN_BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string LOGIN_BUTTON_SIGN_IN {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string LOGIN_BUTTON_TRY_AGAIN {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in failed.
        /// </summary>
        public static string LOGIN_MESSAGE_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_MESSAGE_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check you credentials and try again. Close this window to continue..
        /// </summary>
        public static string LOGIN_TEXT_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_TEXT_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LOGIN_TEXTBOX_EMAIL_PLACEHOLDER {
            get {
                return ResourceManager.GetString("LOGIN_TEXTBOX_EMAIL_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LOGIN_TEXTBOX_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("LOGIN_TEXTBOX_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in.
        /// </summary>
        public static string LOGIN_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string MENU_COMPANY {
            get {
                return ResourceManager.GetString("MENU_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string MENU_LOG_OUT {
            get {
                return ResourceManager.GetString("MENU_LOG_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to.
        /// </summary>
        public static string MENU_NAVIGATE_TO {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string MENU_NAVIGATE_TO_FLOOR {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        public static string MENU_NAVIGATE_TO_FLOORS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_FLOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string MENU_NAVIGATE_TO_ITEMS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        public static string MENU_NAVIGATE_TO_KITCHEN {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_KITCHEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string MENU_NAVIGATE_TO_MENUS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_MENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        public static string MENU_NAVIGATE_TO_MONITORS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_MONITORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string MENU_NAVIGATE_TO_ORDER {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string MENU_NAVIGATE_TO_ORDERS {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string MENU_NAVIGATE_TO_SERVICES {
            get {
                return ResourceManager.GetString("MENU_NAVIGATE_TO_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MENU_PROFILE {
            get {
                return ResourceManager.GetString("MENU_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string MENU_REPORTS {
            get {
                return ResourceManager.GetString("MENU_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string MENU_REPORTS_INVENTORY {
            get {
                return ResourceManager.GetString("MENU_REPORTS_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string MENU_REPORTS_SALES {
            get {
                return ResourceManager.GetString("MENU_REPORTS_SALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MENU_USERS {
            get {
                return ResourceManager.GetString("MENU_USERS", resourceCulture);
            }
        }
    }
}
